base/Dockerfile
Hi,
I get the following error, when try to use netdata in kubernetes, so I would like to add such binary to Dockerfile
```
/usr/libexec/netdata/plugins.d/cgroup-network-helper.sh: line 196: lsns: command not found
```
Thanks
=> add lsns command to base image

base/Dockerfile
As part of https://github.com/netdata/netdata/issues/5934 we are required to include nut package from alpine-edge for our runtime docker image.
APK command has been tested manually within a docker container.
Note: I also adjusted the notes at the top of the file
Fixes https://github.com/netdata/netdata/issues/5934
=> netdata/packaging: Add nut as dependency for our base image

base/Dockerfile
Both should have same packages, only difference is that builder image has the *-devel ones on top
=> netdata/helper-images: Align base image with builder image

base/Dockerfile, builder/Dockerfile
This issue Fixes https://github.com/netdata/netdata/issues/6018
we basically did the following:
1) Change the installation path of Judy, so that we can pick it up nicely on the other side.
2) Include the missing lz4 library on base image (lz4-libs). Alpine has a separate package for its libs that netdata needed.
=> netdata/packaging: Fix broken helper images for dbengine-enabled implementation

oses/Dockerfile.opensuse42.3
This is a brand new docker image, so that we can have a ready to run openSuSe environment for our tests and troubleshooting
=> netdata/ci: Add another pre-compiled image to the list

base/Dockerfile, oses/Dockerfile.alpine, oses/Dockerfile.archlinux, oses/Dockerfile.centos6, oses/Dockerfile.centos7, oses/Dockerfile.debian_bookworm, oses/Dockerfile.debian_bullseye, oses/Dockerfile.debian_buster, oses/Dockerfile.debian_stretch, oses/Dockerfile.debian_wheezy, oses/Dockerfile.fedora31, oses/Dockerfile.opensuse15.0, oses/Dockerfile.opensuse15.1, oses/Dockerfile.opensuse_tumbleweed, oses/Dockerfile.ubuntu1404, oses/Dockerfile.ubuntu1904
virsh is a virtualisation command required by a plugin at runtime 
Fixes https://github.com/netdata/netdata/issues/6073
=> netdata/packaging: Add virsh command to base netdata image

oses/Dockerfile.opensuse_tumbleweed
Satisfy cups-devel dependencies so that the [build](https://hub.docker.com/repository/registry-1.docker.io/netdata/os-test/builds/f04d8573-4b23-4e76-8855-150df46aaac8) does not fail
=> Fix build of Opensuse Tumbleweed docker image

.travis.yml, .travis/build.sh, base/Dockerfile, builder/Dockerfile, builder/patches/freeipmi-argp-redefine.patch
Add support for the freeipmi plugin when running in a docker container.
This includes a patch to freeipmi which fixes compilation on C99 compilers, as required for alpine.
Also:
* Move definition of JUDY_VER to above the judy layer so we don't have to rebuild the lower layers on version change.
* Install manually built dependencies into /deps which will allow for easy / quick install into to the netdata/netdata image.
* Use matrix build to speed up travis-ci and prevent timeouts.
=> feat(freeipmi): Add support for freeipmi

oses/Dockerfile.alpine, oses/Dockerfile.fedora31
Currently, both Alpine and Fedora 31 Docker image builds are failing, ironically both due to changes in packaging of Python SQL modules.
For Alpine, this switches to using Python 3.X, as they appear to have removed a number of Python 2.X packages in preparation for 2.X going EOL this April. The switch necessitates also changing which MySQL package we're using for Python, as the `mysqldb` module is not packaged for Python 3.X on Alpine.
Similarly, Fedora 31 has dropped the MySQL-python package, apparently in favor of python-mysql (an equivalent change to the one mentioned above for Arch, just without the Python version switch).
=> Fix failing Docker image builds.

builder/Dockerfile.gcc
Apparently the package for `libuv` has changed from `libuv-devel` to `libuv1-devel`. But this also looked to be missing entirely from the `Dockerfile.gcc` file in the first place? (_not sure_). Either way the build script in `build/build.sh` fails with:
Also fixes #23 
```#!sh
prologic@Jamess-iMac
Thu Jan 02 10:47:39
~/NetData/netdata
(master) 0
$ docker run --rm -it     --env IS_CONTAINER=TRUE     --volume "${PWD}:/project:Z"     --workdir "/project"     netdata/builder:gcc     ./build/build.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I build/m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader …
```
=> Add missing libuv1-devel dependency

base/Dockerfile
This is required for `usermod` in https://github.com/netdata/netdata/blob/7bcb8c4148d7b303ef6e6cb145445f320af2b073/packaging/docker/run.sh#L24: `/usr/sbin/run.sh: line 24: usermod: command not found`.
=> Add shadow package required for usermod in run.sh

oses/Dockerfile.alpine
Fixes the image build error in https://hub.docker.com/repository/registry-1.docker.io/netdata/os-test/builds/40942ebc-80c4-43de-8007-9ae86ed08a9d
Verified by looking for the _right_ package:
```#!sh
prologic@Jamess-iMac
Sat Jan 04 15:11:19
~
0
$ dki -t --rm alpine:latest /bin/sh
/ # apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
v3.11.2-25-g58afcd742e [http://dl-cdn.alpinelinux.org/alpine/v3.11/main]
v3.11.2-24-g7cfe3a1534 [http://dl-cdn.alpinelinux.org/alpine/v3.11/community]
OK: 11261 distinct packages available
/ # apk search mysql | grep py
py3-mysqlclient-1.3.14-r3
/ #
```
=> Fix netdata/os-test:alpine image with correct py3-mysqlclient package

package-builders/Dockerfile.debian_jessie
This was causing the build to fail. Missed when #31 was merged because I forgot to retest the Jessie image.
=> Fix a typo in the package builder Dockerfile for Debian Jessie.

package-builders/debian-build.sh
This changes how the source and artifacts directories are handled during builds for Debian packages in the following ways:
* The actual build is run in a copy of the sources that's local to the container. This ensures that the build leaves nothing it shouldn't in the user's source directory.
* The artifacts directory and it's contents are modified to have the same ownership as the original source directory.
Both of these are important on Linux systems because the scripts inside the container run as UID 0, which means that the files and directories produced in the source directory by the build are owned by root, and therefore it may not be possible for a regular user to remove them without explicitly elevating to EUID 0.
This is a non-issue on Mac and Windows systems because of how they …
=> Better isolate the sources from the build process.

package-builders/Dockerfile.opensuse15.0, package-builders/Dockerfile.opensuse15.1
This reverts commit a59515740d6f4deb7b319c92011680b4dd752fc8.
As discussed we can do the image aliasing one step up where we need it in netdata/netdata#7735 when we integrate that work into a new packaging CI/CD flows.
=> Revert "Use renamed/aliases opensuse images"

package-builders/Dockerfile.debian_bullseye_i386, package-builders/Dockerfile.debian_buster_i386, package-builders/Dockerfile.debian_jessie_i386, package-builders/Dockerfile.debian_stretch_i386, package-builders/Dockerfile.ubuntu1604_i386, package-builders/Dockerfile.ubuntu1804_i386, package-builders/Dockerfile.ubuntu1904_i386, package-builders/Dockerfile.ubuntu1910_i386
These are needed so that we can build 32-bit x86 packages for these distributions to achieve parity between the current packaging using LXC and the new packaging workflow using Docker. This will eventually be obsoleted by the new `docker buildx` functionality once that's stable enough for us to use it.
Packages using the new images have been verified to build, install, and run correctly.
Tagging for these images is still TBD.
=> Add 32-bit x86 package builder images for Debian and Ubuntu.

builder/Dockerfile
It's required for LWS support in the Docker images.
=> Add cmake to builder image.

package-builders/Dockerfile.centos7, package-builders/Dockerfile.centos8, package-builders/Dockerfile.debian_bullseye, package-builders/Dockerfile.debian_bullseye_i386, package-builders/Dockerfile.debian_buster, package-builders/Dockerfile.debian_buster_i386, package-builders/Dockerfile.debian_jessie, package-builders/Dockerfile.debian_jessie_i386, package-builders/Dockerfile.debian_stretch, package-builders/Dockerfile.debian_stretch_i386, package-builders/Dockerfile.fedora29, package-builders/Dockerfile.fedora30, package-builders/Dockerfile.fedora31, package-builders/Dockerfile.opensuse15.0, package-builders/Dockerfile.opensuse15.1, package-builders/Dockerfile.ubuntu1604, package-builders/Dockerfile.ubuntu1604_i386, package-builders/Dockerfile.ubuntu1804, package-builders/Dockerfile.ubuntu1804_i386, package-builders/Dockerfile.ubuntu1904, package-builders/Dockerfile.ubuntu1904_i386, package-builders/Dockerfile.ubuntu1910, package-builders/Dockerfile.ubuntu1910_i386
This is needed so that we can bundle libwebsockets properly.
=> Add cmake to package builders.

package-builders/Dockerfile.debian_bullseye, package-builders/Dockerfile.debian_bullseye_i386, package-builders/Dockerfile.debian_buster, package-builders/Dockerfile.debian_buster_i386, package-builders/Dockerfile.debian_stretch, package-builders/Dockerfile.debian_stretch_i386, package-builders/Dockerfile.ubuntu1604, package-builders/Dockerfile.ubuntu1604_i386, package-builders/Dockerfile.ubuntu1804, package-builders/Dockerfile.ubuntu1804_i386, package-builders/Dockerfile.ubuntu1904, package-builders/Dockerfile.ubuntu1904_i386, package-builders/Dockerfile.ubuntu1910, package-builders/Dockerfile.ubuntu1910_i386
As in the title.
Debian 9 is the big offender here, as it somehow is missing a bunch of required build dependencies.
This is a blocker for netdata/netdata#8065
=> Add missing dependencies to Debian and Ubuntu package builders.

.github/workflows/base-builder.yml, .github/workflows/oses.yml, .github/workflows/package-builders.yml
The previously added condition checking on the actor that triggered the
workflow does not actually work correctly to limit when publishing
happens (namely, it prevents it from working for almost anybody in the
master repo, and will cause it to be attempted in forks).
This updates the conditions to use the following logic overall:
* The jobs will run on push events on all repos.
* The jobs will run on PR's on all repos.
* The jobs will run on the cron schedule only if not in a fork.
* Publishing will only happen on push and schduled runs in the main
repo.
=> Correctly limit publishing and runs of the workflows.

package-builders/suse-build.sh
This fixes a bug introduced by #63 in the OpenSUSE package build script.
=> Fix invalid path in OpenSUSE package build script.

package-builders/Dockerfile.debian10, package-builders/Dockerfile.debian10_i386, package-builders/Dockerfile.debian11, package-builders/Dockerfile.debian11_i386, package-builders/Dockerfile.debian8, package-builders/Dockerfile.debian8_i386, package-builders/Dockerfile.debian9, package-builders/Dockerfile.debian9_i386, package-builders/Dockerfile.ubuntu1604, package-builders/Dockerfile.ubuntu1604_i386, package-builders/Dockerfile.ubuntu1804, package-builders/Dockerfile.ubuntu1804_i386, package-builders/Dockerfile.ubuntu1910, package-builders/Dockerfile.ubuntu1910_i386, package-builders/debian-build.sh
This is the PR that goes along with netdata/netdata#8468 to fix netdata/netdata#8405
This basically consists of a few things:
- Removing the `ARG`(s) as these are notneeded as we only really care about mutating the runtime enviornment for a build not the builder image itself.
- Moving the `COPY` for the `/build.sh1` further down to better utilise the Docker cache
- Add `systemd` as a dependency so the build and packaging system can figure out which version of SystemD to build/package against.
=> Amend package-builder images for Debian/Ubuntu

base/Dockerfile
=> Add MongoDB support to the netdata/base Docker iamge that the netdata/netdata Docker images uses

base/Dockerfile, builder/Dockerfile, package-builders/Dockerfile.opensuse15.1
This is needed to have JSON-C as a required dependency.
This is the first half of netdata/netdata#8775
=> Add JSON-C dependency to our Dockerfiles.

.github/scripts/build-base-builder-multiarch-images.sh, base/Dockerfile, builder/Dockerfile, package-builders/Dockerfile.centos8
To also support the mongoDB export feature of NetData, the mongo-c-driver-dev package is required.
This PR refers to this Issue [#9479](https://github.com/netdata/netdata/issues/9479) from the netdata/netdata Repository.
=> Add mongo-c-driver-dev library to builder and base image

base/Dockerfile
Add `msmtp` package for sending emails via smtp + tls
Docs: https://learn.netdata.cloud/docs/agent/health/notifications/email
=> Add msmtp to base image

base/Dockerfile, base/requirements.txt, builder/Dockerfile, builder/requirements.txt
Refactos the base/builder Docker images to ensure that we build Python
dependencies as Wheel(s) (_binary Python pakcages_), do this in the builder
image and only ensure we only have runtime dependencies in the base image.
=> Fix netdata/netdata Docker image size

builder/Dockerfile
It's needed by the libJudy build process in our new bundling code.
Required to fix the Docker build checks for https://github.com/netdata/netdata/pull/9776
=> Add libtool to our builder image.

builder/Dockerfile
In the interest of better consistency with the other installation methods, this PR removes the bundling of libJudy that we were doing for our Docker images so that we use the code from https://github.com/netdata/netdata/pull/9776 instead. This will shorten the build timesfor our builder images, but slightly lengthen the total build time for our actual Docker images, but should make any issues relating to libJudy easier to debug as well as ensuring we're 100% consistent with how we handle libJudy on Alpine systems in general.
=> Stop bundling Judy in the builder image.

base/Dockerfile, builder/Dockerfile
I am trying to use the [promethus remote write](https://learn.netdata.cloud/docs/agent/exporting/prometheus/remote_write) functionality, but it says that I need to install snappy & protobuf and re-install netdata from source. However, I do not see such dependencies in [the netdata dockerfile](https://github.com/netdata/netdata/blob/master/packaging/docker/Dockerfile), neither do I see from [netdata:builder](https://hub.docker.com/r/netdata/builder/dockerfile) (or [here](https://github.com/netdata/helper-images/blob/master/builder/Dockerfile)). After some help from the kind maintainers, I try to create this PR to fix this problem.
See: https://github.com/netdata/netdata/issues/9851
=> Snappy & protobuf installation in docker image in order to use "Prometheus remote write"

base/Dockerfile
This allows QoS monitoring to work correctly in a container.
Fixes: https://github.com/netdata/netdata/issues/9861
=> Add `tc` command to our Docker images.

base/Dockerfile
Fixes #91 by adding the `edge/main` repo to the nut installation `apk` invocation such that it can find the `net-snmp-libs` package (which has moved from `edge/testing` to `edge/main`.
=> Add edge/main repository when installing nut

.github/dependabot.yml, .github/workflows/base-builder.yml, .github/workflows/oses.yml, .github/workflows/package-builders.yml, base/Dockerfile, builder/Dockerfile, package-builders/Dockerfile.centos8
This makes the workflows themselves much simpler, increases parallelism of the image builds, enables us to use the regular Alpine images as bases instead of the custom multiarch ones, and will make things much more maintainable.
It also adds configuration to leverage Dependabot to automatically open PRs to keep our GHA workflows updated, as well as the base and builder Docker images, and additionally does some optimization in the Dockerfile for the builder image to cut down on how long it takes to build the image (which is important because of how the new image building and publishing CI/CD works).
=> Update actions workflows to use official Docker actions.

.github/workflows/base-builder.yml
We will eventually pivot to using this instead of the architecture tags for our actual image builds.
This was unfortunately missed with the CI updates to use official Docker actions.
=> Explicitly push `latest` tag for base and builder images.

package-builders/Dockerfile.debian10, package-builders/Dockerfile.debian11, package-builders/Dockerfile.debian9
We do not need `dh-systemd` in Debian 10 or 11 (it’s contents got folded into the base `debhelper` package), and we should be pulling in `g++` on Debian 9.
=> Fix dependencies in Debian package-builder images.

.github/workflows/base-builder.yml
This updates the base and builder image build workflows to leverage the Docker registry for caching. This has a number of tangible benefits:
* CI checks for these images should run much faster.
* Actual builds for deployment of these images should run much faster in most cases.
* Because we’re properly reusing cached layer information, users should need to pull fewer layers when updating their copies of Docker images.
These benefits will require at least 48 hours to be realized however, as the existing images do not have the relevant caching information embedded.
=> AAdd build caching for base and builder images.

.github/workflows/package-builders.yml, package-builders/Dockerfile.centos8, package-builders/Dockerfile.fedora32, package-builders/Dockerfile.fedora33
Also adds comments listing other possible architectures for each distro.
This does not add any additional platforms for CentOS as we are dependent on a repository that is only available for x86 systems.
We’ll probably eventually add POWER8 (`linux/ppc64le`) and System/Z (`linux/s390x`) support as well, but those need proper testing that has not yet been done.
=> Add ARM package builder images.

.github/workflows/package-builders.yml, package-builders/Dockerfile.fedora34, package-builders/Dockerfile.ubuntu21.04
Planned release of Ubuntu 21.04 is 2021-04-22.
Planned release of Fedora 34 is 2021-04-20.
This PR should ideally be merged prior to then so that we can have binary package support for both on day one.
=> Add Ubuntu 21.04 and Fedora 34 package builder images.

package-builders/Dockerfile.centos7, package-builders/Dockerfile.centos8, package-builders/Dockerfile.debian10, package-builders/Dockerfile.debian11, package-builders/Dockerfile.debian9, package-builders/Dockerfile.fedora32, package-builders/Dockerfile.fedora33, package-builders/Dockerfile.fedora34, package-builders/Dockerfile.opensuse15.2, package-builders/Dockerfile.ubuntu16.04, package-builders/Dockerfile.ubuntu18.04, package-builders/Dockerfile.ubuntu20.04, package-builders/Dockerfile.ubuntu20.10, package-builders/Dockerfile.ubuntu21.04
It seems to not be run automatically in some cases, which causes the package builds to eventually fail.
=> Explicitly run `c_rehash` when building the package builders.

.github/workflows/package-builders.yml
See netdata/netdata#11057 for rationale.
=> Limit maximum concurrent jobs for package-builder CI.

.github/workflows/package-builders.yml
It was originally not included due to the upstream Docker image not supporting 32-bit ARM.
=> Add 32-bit ARM Fedora 34 package builder image.

package-builders/Dockerfile.debian11
We need an additional dependency on Debian 11 to get the FreeIPMI plugin to build correctly.
=> Fix IPMI dependency in Debian 11 package builder.

package-builders/Dockerfile.ubuntu16.04
We should be copying the entrypoint script to it’s own file.
=> Fix error in Ubuntu 16.04 package builder.

package-builders/entrypoint.sh
Instead of exiting with a 0 exit status and then failing on a later step due to a lack of properly build packages.
=> Actually return a non-zero exit on a package build failure.

package-builders/debian-build.sh
Instead of assuming the CPU architecture will match the system architecture, just check through all the configured pkg-config paths for the known bogus file and fix it if found.
This fixes the 32-bit x86 native package builds for Debian 11.
=> Properly handle bogus pkg-config file on Debian systems.

.github/workflows/package-builders.yml, package-builders/Dockerfile.ubuntu21.04, package-builders/Dockerfile.ubuntu21.10
Expected release of Ubuntu 21.10 is 2021-10-14.
=> Add Ubuntu 21.10 package builder images.

.github/workflows/package-builders.yml, package-builders/Dockerfile.oraclelinux8, package-builders/oraclelinux8-codeready.repo
This is only adding OL8 as we cannot support OL6 (for the same reasons we can’t build for CentOS 6) and OL7 has a number of ridiculous complexities that are probably not worth working around.
We have to use a pre-generated repo config file for the OL8 CodeReady repo as there is no way other than manually creating the file to enable it for OL8.
=> Add Oracle Linux 8 package builder.

.github/workflows/package-builders.yml, package-builders/Dockerfile.rockylinux8
Long-term this will replace our CentOS 8 package builder image.
=> Add Rocky Linux 8 package builder image.

package-builders/debian-build.sh, package-builders/fedora-build.sh, package-builders/suse-build.sh
This removes the `.git` directory from the source directory we are using to perform package builds before actually building the packages, ensuring they utilize the `packaging/version` file to determine the version number instead of running `git describe`.
Fixes: https://github.com/netdata/netdata/issues/12333
=> Handle package versioning correctly.

base/Dockerfile, builder/Dockerfile
* Remove NodeJS from the builder image, as it’s not actually used at build time (it will be removed from the base image at a later date, when we finally switch to Go for SNMP data collection support).
* Sort the dependency lists so that they are easier to maintain long-term.
* Add apcupsd to the base image, to make the APC UPS data collector work properly.
* Use lm-sensors from the regular repos instead of the edge repos, as it’s the same version there now.
Fixes: netdata/netdata#12346
=> Assorted cleanup of our Docker images.

base/Dockerfile
It’s made it into the community repo in Alpine Edge, so pull from there instead of trying to pull from testing.
This fixes a build error in the base image build.
=> Change source of NUT package in base image.

base/Dockerfile, builder/Dockerfile, static-builder/Dockerfile
This will update our Docker images and static builds to use Alpine 3.16 as a base.
=> Bump Alpine helper images to 3.16

base/requirements.txt, builder/requirements.txt
Should be merged after v1.36.0 is out.
---
Python Postgres collector is [expected to be removed](https://github.com/netdata/netdata/pull/13503) after the v1.36.0 release.
=> remove psycopg2 from requirements

base/Dockerfile
> **Warning**: should be merged a bit later after we ensure there won't be v1.37.1
On the other hand, we can get it back if/when we need (I hope never) v1.37.1?
---
In accordance with [v1.37.0 deprecation notice](https://github.com/netdata/netdata/releases/tag/v1.37.0#v1370-deprecation).
PR in netdata/netdata is https://github.com/netdata/netdata/pull/14073.
=> remove fping

static-builder/Dockerfile
We need the static builds of `libmnl` for the `libnetfilter_acct`
Signed-off-by: Tasos Katsoulas <tasos@netdata.cloud>
=> Update base image

.github/workflows/package-builders.yml
remove an oversight from our ci
=> cleanup parorama (fedora 35)

base/Dockerfile
We use `tput` in the `edit-config` script, so we should make sure it’s available in our Docker images, which means we need to install `ncurses`.
=> Add ncurses to our base Docker image so tput is available.

.github/workflows/base-builder.yml, .github/workflows/package-builders.yml, .github/workflows/static-builder.yml
The current structure of the CI workflows for building the Docker images in this repo is directly based on the structure of the Docker build workflow in https://github.com/netdata/netdata.  However, this repo doesn’t need to do any runtime checks prior to publishing the images, so the build check jobs largely just waste time when the workflow is running to publish the images.
Given this, it makes sense to just decouple the build-check jobs from the publishing jobs.
This results in a significant improvement in the time it takes to publish the images after a PR is merged, as well as reducing the overall impact on other CI.
=> Skip build checks when publishing images.

base/Dockerfile, builder/Dockerfile, static-builder/Dockerfile
They apparently are needed by the build process.
=> Add ZSTD headers and libraries to builder images.

package-builders/Dockerfile.opensuse15.4, package-builders/Dockerfile.opensuse15.5, package-builders/Dockerfile.opensusetumbleweed
This should fix the failures on 15.4.
=> Make openSUSE package builder image builds more robust.

static-builder/Dockerfile
want this for sentry, but we can also may get rid of this https://github.com/netdata/netdata/blob/master/packaging/makeself/jobs/50-curl-7.87.0.install.sh
cc @Ferroin
=> add curl static to static-builder image

package-builders/Dockerfile.almalinux8, package-builders/Dockerfile.oraclelinux8
```python
√ helper-images % ack curl package-builders/Dockerfile.almalinux8
curl \
libcurl-devel \
```
=> Fixed double libcurl in rpm packages

.github/workflows/package-builders.yml, package-builders/Dockerfile.rockylinux8, package-builders/Dockerfile.rockylinux9
Alma Linux has formally announced they are no longer trying for 1:1 compatibility with RHEL, which makes them a less than ideal choice for us to use as a build platform for our native packages. We still can’t use the RHEL universal base images as a base because of RH’s absurdist views on the usability of their platform, so Rocky Linux is our next best choice.
Once this is merged there will be an associated PR in https://github.com/netdata/netdata/ to move the CI there to use these new images.
=> Switch to Rocky Linux as base for EL package builders.

ansible-docker/Dockerfile.ubuntu1804, ansible-docker/Dockerfile.ubuntu2004, ansible-docker/Dockerfile.ubuntu2204
Dockerfiles to generate images for testing netdata-ansible using Ansible Molecule.
Ubuntu 18.04
Ubuntu 20.04
Ubuntu 22.04
Note that these dockerfiles/images are provisional as they should enable systemd support but have not been tested yet.
=> Initial commit of dockerfiles which will be used to test netdata-ansible

package-builders/Dockerfile.opensuse15.4, package-builders/Dockerfile.opensuse15.5
The actual issue is upstream, but this should work around it.
=> Fix broken openSUSE package-builder images.

.github/workflows/package-builders.yml, package-builders/Dockerfile.fedora39
Betas are out as of 2023-09-20, expected release date is some time before 2023-10-31.
=> Add Fedora 39 package builder images.

package-builders/Dockerfile.debian10, package-builders/Dockerfile.debian11, package-builders/Dockerfile.debian12, package-builders/Dockerfile.ubuntu20.04, package-builders/Dockerfile.ubuntu22.04, package-builders/Dockerfile.ubuntu23.04
32-bit ARM specifically ships a broken version, so use the absolute latest we can get instead of the copy from the official repos.
Also, upgrade system packages when prepping DEB-based package builders.
=> Fix handling of CMake in Ubuntu 20.04.

package-builders/Dockerfile.amazonlinux2, package-builders/Dockerfile.centos7
Without this, AL2 builds for AArch64 fail since they have they wrong copy of CMake.
=> Properly pull 64-bit ARM copies of CMake when needed.

.github/data/matrices.yaml, base/Dockerfile.v2, builder/Dockerfile.v2
Rationale and testing procedure can be found in https://github.com/netdata/netdata/pull/15823.
This should not be merged until shortly before https://github.com/netdata/netdata/pull/15823 is scheduled to be merged, as it will break the existing Docker image build process.
Includes some cleanup in the builder image to drop packages that we really do not need there.
=> Switch to using Debian as a base for our Docker images.

package-builders/Dockerfile.amazonlinux2.v1, package-builders/Dockerfile.amazonlinux2023.v1, package-builders/Dockerfile.centos-stream8.v1, package-builders/Dockerfile.centos-stream9.v1, package-builders/Dockerfile.centos7.v1, package-builders/Dockerfile.debian10.v1, package-builders/Dockerfile.debian11.v1, package-builders/Dockerfile.debian12.v1, package-builders/Dockerfile.fedora37.v1, package-builders/Dockerfile.fedora38.v1, package-builders/Dockerfile.fedora39.v1, package-builders/Dockerfile.opensuse15.4.v1, package-builders/Dockerfile.opensuse15.5.v1, package-builders/Dockerfile.opensusetumbleweed.v1, package-builders/Dockerfile.oraclelinux8.v1, package-builders/Dockerfile.oraclelinux9.v1, package-builders/Dockerfile.rockylinux8.v1, package-builders/Dockerfile.rockylinux9.v1, package-builders/Dockerfile.ubuntu20.04.v1, package-builders/Dockerfile.ubuntu22.04.v1, package-builders/Dockerfile.ubuntu23.04.v1, package-builders/Dockerfile.ubuntu23.10.v1
They are already present in the OCI base images and static-builder images.
=> Add ZSTD libraries to package builder images.

static-builder/Dockerfile.v1
Fix bash dependency for static builds
=> Add ncurse-static to our static builds

static-builder/Dockerfile.v1
Reverts netdata/helper-images#257
This unexpectedly broke our static builds.
=> Revert "Bump alpine from 3.18 to 3.19 in /static-builder"

static-builder/Dockerfile.v1, static-builder/snappy.pc
Fixes: netdata/netdata#16677
The upstream snappy sources don’t include a pkg-config file.
Test:
- build `netdata/static-builder:v1` using this branch.
- build/install Netdata static.
- check Prometheus remote write in the build info - OK.
- configure Prometheus remote write exporter, and make sure that it exports data - OK.
=> static builder: add snappy.pc

package-builders/Dockerfile.debian10.v1, package-builders/Dockerfile.debian11.v1, package-builders/Dockerfile.debian12.v1, package-builders/Dockerfile.ubuntu20.04.v1, package-builders/Dockerfile.ubuntu22.04.v1, package-builders/Dockerfile.ubuntu23.10.v1
Add sentry-cli to all deb based system (exclude ubuntu 23.04, upcoming eol)
=> Add sentry-cli to all deb based system 

package-builders/Dockerfile.debian10.v1, package-builders/Dockerfile.debian11.v1, package-builders/Dockerfile.debian12.v1, package-builders/Dockerfile.ubuntu20.04.v1, package-builders/Dockerfile.ubuntu22.04.v1, package-builders/Dockerfile.ubuntu23.10.v1
- Use the same command for downloading regardless of distro.
- Add options to ensure that cURL handles issues properly and fails cleanly in error cases.
- Use one line per command (easier to read and reason about).
- Remove the install script in the same RUN step that added it so that it doesn’t actually contribute to the final image size and also avoids a pointless extra layer.
=> Clean up installation of Sentry in package-builders.

package-builders/debian-build.sh
This is preparation for moving the `contrib/debian` directory to the root of the source tree, where all Debian tooling expects it to be.
With this PR, the package builders will correctly handle both the existing structure of the repo and the planned updated structure.
=> Only copy debian directory if needed.

static-builder/Dockerfile.v1
It's an attempt, during updating OpenSSL and curl for our static builds fail because this package is missing.
Merging it after upcoming nightly build
=> Add libpsl-static to static builders

package-builders/debian-build.sh, package-builders/fedora-build.sh, package-builders/suse-build.sh
This will be needed by the upcoming Go plugin integration in our packaging code.
We need to explicitly list Go as a build dependency in our packaging files so that users who build without using our package builders have things fail cleanly, but we need to mask that build dependency when building in our package builders since we universally use a copy of the official Go toolchain instead of the distro-provided toolchain to ensure that we have a working toolchain.
For DEB packages, this requires modifying the `debian/control` file in-place before building to remove the dependency.
For RPM packages, we instead use a macro that is only defined by our build infrastructure at build time to skip those dependencies.
=> Add handling of golang deps to package builder images.

package-builders/fedora-build.sh, package-builders/suse-build.sh
Just noticed the
> /build.sh: line 23: /netdata/packaging/go.d.version: No such file or directory
error in the netdata/netdata ci logs and decided to fix it!
=> remove using of netdata/packaging/go.d.version

package-builders/Dockerfile.debian10.v1, package-builders/Dockerfile.debian11.v1, package-builders/Dockerfile.debian12.v1, package-builders/Dockerfile.ubuntu20.04.v1, package-builders/Dockerfile.ubuntu22.04.v1, package-builders/Dockerfile.ubuntu23.10.v1, package-builders/Dockerfile.ubuntu24.04.v1
We actually depend on it in our package build process, but it was not explicitly listed in the pacakges we were installing, instead being pulled in as an implicit transitive dependency of the debhelper plugins we pulled in (which we don’t actually _need_ anymore).
=> Make debhelper an explicit dependency in Debian/Ubuntu package builders

.github/data/matrices.yaml, package-builders/Dockerfile.debian10.v2, package-builders/Dockerfile.debian11.v2, package-builders/Dockerfile.debian12.v2, package-builders/Dockerfile.ubuntu20.04.v2, package-builders/Dockerfile.ubuntu22.04.v2, package-builders/Dockerfile.ubuntu23.10.v2, package-builders/Dockerfile.ubuntu24.04.v2, package-builders/cpack-deb.sh
Actual build will be handled by a script in the agent source tree, but we still need the basic infra around it in the package builders.
=> Add DEB package builders for new CPack infra.

static-builder/Dockerfile.v1
- Add coreutils (needed by libbpf build)
- Pull in the correct package to get a working `ninja` command for builds.
- Remove trailing spaces.
=> Assorted fixes for the static builder image.

.github/data/matrices.yaml, package-builders/Dockerfile.opensuse15.6.v1, package-builders/Dockerfile.opensuse15.6.v2
=> Add openSUSE Leap 15.6 package builders.

.github/data/matrices.yaml, package-builders/Dockerfile.fedora41.v1, package-builders/Dockerfile.fedora41.v2, package-builders/Dockerfile.ubuntu24.10.v1, package-builders/Dockerfile.ubuntu24.10.v2
Both are expected to release next moth.
=> Add package builders for Fedora 41 and Ubuntu 24.10.

base/Dockerfile.v2, builder/Dockerfile.v2
Also tweak the cases where we were checking `uname -m` to use `dpkg-architecture --equals` instead, as it is far more reliable.
=> Add dpkg-dev to Docker builder image (for `dpkg-architecture` command).

static-builder/Dockerfile.v1
=> Drop libunwind from v1 static builders and include build deps for it to be vendored at build time.

.github/data/matrices.yaml, package-builders/Dockerfile.centos-stream10.v1, package-builders/Dockerfile.centos-stream10.v2, package-builders/Dockerfile.fedora42.v1, package-builders/Dockerfile.fedora42.v2, package-builders/Dockerfile.ubuntu25.04.v2
- Add builders for CentOS Stream 10, Fedora 42, and Ubuntu 25.04
- Stop building EOL platforms.
- Stop building v1 builder images for DEB platforms (they aren’t used anymore).
=> Package builder updates.

scripts/install-rust.sh
Because of how a 32-bit x86 container looks internally, rustup is installing a 64-bit x86 toolchain by default instead of a 32-bit x86 toolchain. This fixes that so that the Rust toolchain properly matches the intended build target.
=> Ensure that 32-bit x86 containers get a 32-bit x86 version of Rust.
