netdata/helper-images

- .travis/build.sh
- base/Dockerfile
- builder/Dockerfile
This PR supports the new Database implementation for Dockerized builds, we inject the required package dependencies on the base images
> netdata/packaging: Add dependencies for Database (PR #5282)

- oses/Dockerfile.alpine
- oses/Dockerfile.centos6
- oses/Dockerfile.centos7
- oses/Dockerfile.ubuntu1604
- oses/Dockerfile.ubuntu1804
Update OS images with all required packages for netdata
> netdata/packaging: Update OS

- oses/Dockerfile.archlinux
> netdata/packaging/ci: Add another distro on the precompiled OS images

- oses/Dockerfile.debian_stretch
- oses/Dockerfile.fedora30
https://github.com/netdata/netdata/issues/6102
> netdata/packaging: remove bats from stretch and add fedora30 image

- oses/Dockerfile.debian_bookworm
- oses/Dockerfile.debian_bullseye
- oses/Dockerfile.debian_buster
- oses/Dockerfile.fedora28
- oses/Dockerfile.fedora29
- oses/Dockerfile.fedora30
* Fix fedora 30 - add find and ps commands (find is critical, ps is for admin during testing)
* Add fedora 29 image
* Add all Debian images up to latest (Only until buster available)
> New docker images and one fix for the fedora image

- oses/Dockerfile.opensuse15.0
- oses/Dockerfile.opensuse15.1
- oses/Dockerfile.opensuse42.3
- oses/Dockerfile.opensuse_tumbleweed
> netdata/packaging: fix judy devel package on suse images

- package-builders/debian-build.sh
Just some minor tweaks to #31 to support a more generalized `Dockerfile` in netdata/netdata#7735
> Debian builder images tweaks

- package-builders/Dockerfile.centos8
Partially fixes netdata/netdata#6967
TODO:
> Adds a CentOS 8 Docker Buidler Image

- .github/workflows/bases_builders_oses.yml
- .github/workflows/docker.yml
v2 is the current version, and v1 seems to have some issues currently on reruns of actions.
> Use version 2 of checkout action.

- package-builders/fedora-build.sh
- package-builders/suse-build.sh
This fixes handling of the paths used in the RPM build process in the RPM builder scripts.
> Fix another bug in the RPM builder scripts.

- .github/scripts/build-base-builder-multiarch-images.sh
- .github/workflows/base-builder.yml
- .github/workflows/oses.yml
- .github/workflows/package-builders.yml
> Publish directly to the Docker Hub using the Docker CLI

- .github/workflows/package-builders.yml
Fixes a typo in the image naming for the package-builder images.
> Fix the name used for the package-builder images.

- package-builders/Dockerfile.centos7
- package-builders/Dockerfile.centos8
- package-builders/Dockerfile.fedora32
- package-builders/Dockerfile.fedora33
- package-builders/Dockerfile.opensuse15.1
- package-builders/Dockerfile.opensuse15.2
Related to netdata/netdata#10507.
> Added libwebsockets to RPM package builders.

- package-builders/Dockerfile.debian10
> Add missing dh-systemd dependency to Debian 10 package builder.

- package-builders/fedora-build.sh
- package-builders/suse-build.sh
> Ensure that versions being used conform to RPM’s brain-dead requirements.

- package-builders/Dockerfile.fedora34
> Use correct base image for Fedora 34 package builders.

- package-builders/Dockerfile.centos8
See https://github.com/netdata/netdata/pull/10973 for context.
> Use correct version of OKay repository setup RPM.

- package-builders/debian-build.sh
- package-builders/fedora-build.sh
- package-builders/suse-build.sh
See https://github.com/netdata/netdata/pull/11157 for details.
> Properly mark the installation type for binary packages.

- .github/workflows/package-builders.yml
- package-builders/Dockerfile.opensuse15.3
> Add OpenSUSE 15.3 package builder image.

- package-builders/fedora-build.sh
- package-builders/suse-build.sh
> Fixed handling of install-type file for RPM builds.

- package-builders/Dockerfile.debian11
- package-builders/debian-build.sh
This adds a workaround for an issue with pkg-config.
> Fix handling of DEB builds for Debian 11.

- .github/workflows/review.yml
Covers Dockerfiles, shell scripts, YAML files, and GHA workflows. This brings linting here in line with what we have in the main agent repo.
> Added GHA workflow to run linters and static checkers.

- package-builders/Dockerfile.centos7
- package-builders/Dockerfile.centos8
> Clean up useless deps from CentOS package builders.

- .github/workflows/base-builder.yml
- builder/Dockerfile
As preparation for adding POWER8+ support to our official Docker images.
> Add POWER8+ images for base and builder images.

- .github/workflows/package-builders.yml
- package-builders/Dockerfile.fedora35
Expected release date is mid to late October.
> Added Fedora 35 packagebuilder images.

- .github/CODEOWNERS
And finally remove @knatsakis.
> Add @maneamarius to CODEOWNERS.

- base/Dockerfile
- builder/Dockerfile
> update alpine image from 3.12 to 3.14

- package-builders/Dockerfile.centos7
- package-builders/Dockerfile.debian10
- package-builders/Dockerfile.debian11
- package-builders/Dockerfile.debian9
- package-builders/Dockerfile.fedora34
- package-builders/Dockerfile.fedora35
- package-builders/Dockerfile.fedora36
- package-builders/Dockerfile.opensuse15.3
- package-builders/Dockerfile.opensuse15.4
- package-builders/Dockerfile.oraclelinux8
- package-builders/Dockerfile.rockylinux8
- package-builders/Dockerfile.ubuntu18.04
- package-builders/Dockerfile.ubuntu20.04
- package-builders/Dockerfile.ubuntu21.10
- package-builders/Dockerfile.ubuntu22.04
Needed for https://github.com/netdata/netdata/pull/12366.
> Add libatomic to package builder images.

- .github/workflows/static-builder.yml
- static-builder/Dockerfile
First part of implementing https://github.com/netdata/netdata/issues/12817.
> Add static-builder image for building static builds of the agent.

- base/Dockerfile
This ensures we pick up bug fixes for it as quickly as possible.
Fix for: https://github.com/netdata/netdata/issues/12937
> Pull fping from Alpine Edge instead of current release.

- .github/workflows/package-builders.yml
- package-builders/Dockerfile.almalinux9
First steps for https://github.com/netdata/netdata/issues/13057
> Add Alma Linux 9 package builder image.

- .github/workflows/package-builders.yml
- package-builders/Dockerfile.oraclelinux9
> Add Oracle Linux 9 package builder images.

- base/Dockerfile
- builder/Dockerfile
- static-builder/Dockerfile
Reverts netdata/helper-images#178
> Revert "Bump base images to Alpine 3.17."

- base/Dockerfile
- builder/Dockerfile
- package-builders/Dockerfile.almalinux8
- package-builders/Dockerfile.almalinux9
- package-builders/Dockerfile.centos7
- package-builders/Dockerfile.debian10
- package-builders/Dockerfile.debian11
- package-builders/Dockerfile.fedora36
- package-builders/Dockerfile.fedora37
- package-builders/Dockerfile.opensuse15.4
- package-builders/Dockerfile.oraclelinux8
- package-builders/Dockerfile.oraclelinux9
- package-builders/Dockerfile.ubuntu18.04
- package-builders/Dockerfile.ubuntu20.04
- package-builders/Dockerfile.ubuntu22.04
- package-builders/Dockerfile.ubuntu22.10
- static-builder/Dockerfile
This provides slightly better behavior on GHCR, as well as providing some more information for users.
> Add basic OCI labels to our images.

- .github/workflows/package-builders.yml
- package-builders/Dockerfile.debian12
First part of: https://github.com/netdata/netdata/issues/14518
> Add Debian 12 package builder images.

- .github/workflows/package-builders.yml
- package-builders/Dockerfile.amazonlinux2
First step of: https://github.com/netdata/netdata/issues/14199
> Add Amazon Linux 2 package builder images.

- base/Dockerfile
- builder/Dockerfile
- package-builders/Dockerfile.almalinux8
- package-builders/Dockerfile.almalinux9
- package-builders/Dockerfile.amazonlinux2
- package-builders/Dockerfile.centos7
- package-builders/Dockerfile.debian10
- package-builders/Dockerfile.debian11
- package-builders/Dockerfile.debian12
- package-builders/Dockerfile.fedora36
- package-builders/Dockerfile.fedora37
- package-builders/Dockerfile.opensuse15.4
- package-builders/Dockerfile.opensusetumbleweed
- package-builders/Dockerfile.oraclelinux8
- package-builders/Dockerfile.oraclelinux9
- package-builders/Dockerfile.ubuntu18.04
- package-builders/Dockerfile.ubuntu20.04
- package-builders/Dockerfile.ubuntu22.04
- package-builders/Dockerfile.ubuntu22.10
- static-builder/Dockerfile
Adds libyaml to our helper images.
> Add libyaml as a dependency

- .hadolint.yml
1. Adding hadolint config file
2. Add rule to ignore DL3041, we never specify version when we install packages via package manager.
> Add hadolint config file

- .github/workflows/package-builders.yml
- package-builders/Dockerfile.amazonlinux2
- package-builders/Dockerfile.amazonlinux2023
- package-builders/Dockerfile.centos7
- package-builders/Dockerfile.fedora36
- package-builders/Dockerfile.fedora37
- package-builders/Dockerfile.fedora38
- package-builders/Dockerfile.opensuse15.4
- package-builders/Dockerfile.opensusetumbleweed
It was officially released on 2023-03-15.
> Add Amazon Linux 2023 package builder images.

- package-builders/fedora-build.sh
- package-builders/suse-build.sh
Required for: https://github.com/netdata/netdata/pull/14551
> Allow rpmbuild source fetching

- base/Dockerfile
- builder/Dockerfile
To support the systemd-journal plugin.
> Add libelogind to Docker images.

- package-builders/Dockerfile.almalinux8
- package-builders/Dockerfile.almalinux9
- package-builders/Dockerfile.amazonlinux2
- package-builders/Dockerfile.amazonlinux2023
- package-builders/Dockerfile.centos7
- package-builders/Dockerfile.debian10
- package-builders/Dockerfile.debian11
- package-builders/Dockerfile.debian12
- package-builders/Dockerfile.fedora37
- package-builders/Dockerfile.fedora38
- package-builders/Dockerfile.opensuse15.4
- package-builders/Dockerfile.opensuse15.5
- package-builders/Dockerfile.opensusetumbleweed
- package-builders/Dockerfile.oraclelinux8
- package-builders/Dockerfile.oraclelinux9
- package-builders/Dockerfile.ubuntu20.04
- package-builders/Dockerfile.ubuntu22.04
- package-builders/Dockerfile.ubuntu23.04
Needed for https://github.com/netdata/netdata/pull/15363
> Add systemd development files to package builder images.

- package-builders/Dockerfile.centos-stream8
- package-builders/Dockerfile.centos-stream9
Needed for https://github.com/netdata/netdata/pull/15363
> Add systemd development files to package builder images (CentOS-Stream)

- package-builders/Dockerfile.debian10
- package-builders/Dockerfile.debian11
- package-builders/Dockerfile.debian12
- package-builders/Dockerfile.fedora37
- package-builders/Dockerfile.fedora38
- package-builders/Dockerfile.fedora39
- package-builders/Dockerfile.opensuse15.4
- package-builders/Dockerfile.opensuse15.5
- package-builders/Dockerfile.opensusetumbleweed
- package-builders/Dockerfile.ubuntu20.04
- package-builders/Dockerfile.ubuntu22.04
- package-builders/Dockerfile.ubuntu23.04
- static-builder/Dockerfile
> Add dependencies to build xenstat plugin for native packages.

- package-builders/Dockerfile.amazonlinux2
- package-builders/Dockerfile.centos-stream8
- package-builders/Dockerfile.centos-stream9
- package-builders/Dockerfile.centos7
- package-builders/Dockerfile.debian10
- package-builders/Dockerfile.debian11
- package-builders/Dockerfile.debian12
- package-builders/Dockerfile.fedora37
- package-builders/Dockerfile.fedora38
- package-builders/Dockerfile.fedora39
- package-builders/Dockerfile.oraclelinux8
- package-builders/Dockerfile.oraclelinux9
- package-builders/Dockerfile.rockylinux8
- package-builders/Dockerfile.rockylinux9
- package-builders/Dockerfile.ubuntu20.04
- package-builders/Dockerfile.ubuntu22.04
- package-builders/Dockerfile.ubuntu23.04
- package-builders/ol8-epel.repo
- package-builders/ol9-epel.repo
- static-builder/Dockerfile
> Add MongoDB exporter deps to package builders and static builder.

- .github/workflows/base-builder.yml
- .github/workflows/package-builders.yml
- .github/workflows/static-builder.yml
- package-builders/Dockerfile.ubuntu20.04
Designed to be consistent with how the equivalent logic in netdata/netdata works.
> Update CI workflows to skip running on PRs which they do not apply to.

- .github/data/matrices.yaml
- package-builders/Dockerfile.ubuntu23.10.v1
New ubuntu release is out, https://discourse.ubuntu.com/t/mantic-minotaur-release-notes/35534?_ga=2.152441401.1432582049.1697194186-535877025.1695600723 lets include this in our supported native packages.
> Add mantin minotaur

- package-builders/Dockerfile.amazonlinux2.v1
- package-builders/Dockerfile.amazonlinux2023.v1
- package-builders/Dockerfile.centos-stream8.v1
- package-builders/Dockerfile.centos-stream9.v1
- package-builders/Dockerfile.centos7.v1
- package-builders/Dockerfile.debian10.v1
- package-builders/Dockerfile.debian11.v1
- package-builders/Dockerfile.debian12.v1
- package-builders/Dockerfile.fedora37.v1
- package-builders/Dockerfile.fedora38.v1
- package-builders/Dockerfile.fedora39.v1
- package-builders/Dockerfile.opensuse15.4.v1
- package-builders/Dockerfile.opensuse15.5.v1
- package-builders/Dockerfile.opensusetumbleweed.v1
- package-builders/Dockerfile.oraclelinux8.v1
- package-builders/Dockerfile.oraclelinux9.v1
- package-builders/Dockerfile.rockylinux8.v1
- package-builders/Dockerfile.rockylinux9.v1
- package-builders/Dockerfile.ubuntu20.04.v1
- package-builders/Dockerfile.ubuntu22.04.v1
- package-builders/Dockerfile.ubuntu23.04.v1
- package-builders/Dockerfile.ubuntu23.10.v1
Part one to support https://github.com/netdata/netdata/pull/16357
> Add libpcre2-8 to native packages

- base/Dockerfile.v1
- builder/Dockerfile.v1
- static-builder/Dockerfile.v1
Refs https://github.com/netdata/netdata/pull/16357
> Add pcre2-dev for static builds

- .github/data/matrices.yaml
> Add ARMv6 static builder images.

- static-builder/Dockerfile.v1
Needed for https://github.com/netdata/netdata/pull/16962
> Add libidn2 packages into our static builder

- .github/data/matrices.yaml
- package-builders/Dockerfile.fedora40.v1
> Add Fedora 40 package builder images.

- .github/data/matrices.yaml
- package-builders/Dockerfile.ubuntu24.04.v1
> Add Ubuntu 24.04 package builder images.

- .github/data/matrices.yaml
- package-builders/Dockerfile.amazonlinux2.v2
- package-builders/Dockerfile.amazonlinux2023.v2
- package-builders/Dockerfile.centos-stream8.v2
- package-builders/Dockerfile.centos-stream9.v2
- package-builders/Dockerfile.centos7.v2
- package-builders/Dockerfile.fedora39.v2
- package-builders/Dockerfile.fedora40.v2
- package-builders/Dockerfile.opensuse15.5.v2
- package-builders/Dockerfile.opensusetumbleweed.v2
- package-builders/Dockerfile.oraclelinux8.v2
- package-builders/Dockerfile.oraclelinux9.v2
- package-builders/Dockerfile.rockylinux8.v2
- package-builders/Dockerfile.rockylinux9.v2
- package-builders/cpack-deb.sh
- package-builders/cpack-rpm.sh
- Fix distro name embedding for CPack DEB packages.
- Add package builders for CPack RPM packages.
> Package builder updates.

- .github/data/matrices.yaml
- .github/scripts/gen-matrix-static.py
- static-builder/Dockerfile.v2
Based on Debian 13 prerelease images due to some of our build requirements not being present in Debian 12 (and backports being even more likely to break things).
> Add Debian-based static builder images.

- static-builder/Dockerfile.v1
> Add libunwind to v1 static builder images.

- .github/workflows/base-builder.yml
- .github/workflows/legacy.yml
- .github/workflows/package-builders.yml
- .github/workflows/static-builder.yml
The action has been compromised and should not be used in CI any more.
> Remove tj-actions/changed-files action from CI.

- .github/data/matrices.yaml
- package-builders/Dockerfile.rockylinux10.v1
- package-builders/Dockerfile.rockylinux10.v2
> Add Rocky Linux 10 package builder images.

- .github/data/matrices.yaml
- package-builders/Dockerfile.oraclelinux10.v1
- package-builders/Dockerfile.oraclelinux10.v2
> Add Oracle Linux 10 package builders.

- base/Dockerfile.v3
- builder/Dockerfile.v3
Also, do a bit of cleanup to account for us not doing 32-bit Docker images starting with Debian 13.
> Fix issues with Debian 13 base image.

- .github/data/matrices.yaml
- package-builders/Dockerfile.opensuse16.0.v1
- package-builders/Dockerfile.opensuse16.0.v2
- package-builders/Dockerfile.ubuntu25.10.v2
> Add openSUSE Leap 16.0 and Ubuntu 25.10 package builders.

- package-builders/suse-build.sh
> Fix package builds for openSUSE 16.0.
